version: '3.6'
services:

  app_api:
    container_name: app_api
    command: python3 myproject/manage.py runserver 0.0.0.0:3889
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3889:3889"
    volumes:
      - .:/app/
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 3889
      LOG_LEVEL: DEBUG

    networks:
      - default
